### ISSUE TITLE
Multiple load seems to be bugged

### ISSUE THREAD

**Issue by resonant-gamedesign** [neubee/spirit-island-builder#267]
I cannot load a different Spirit after loading the first one. The issue is specifically when loading, not when using examples.

**Comment by tomprince** [comment]
I cannot seem to reproduce this, either locally or on the deployed site. At least, not with loading the example files via the "Load" button.

**Comment by resonant-gamedesign** [comment]
OK its working for me now too. Maybe I just needed to wait (can we do a 'loading' overlay of some kind?)

New issue - images not loading.

**Comment by tomprince** [comment]
> New issue

New issue should be in its own github issue.

> images not loading

Is this when loading some of the examples via "Load"? This is because they use relative image URLs, and is expected and unavoidable.

Relative image paths don't work via the "Load" button, since the browser won't let a web page access arbitrary local files (or even know the path of a file that is uploaded). Only `data:` (or `https://`) URLs will work when loading (and `https://` URLs generally won't work with generating an image).

This isn't a problem when loading an example from the site, since in that case we can resolve the URL to an absolute URL (that isn't a cross-site URL).

**Comment by resonant-gamedesign** [comment]
Thanks @tomprince , somehow this issue went away on its own. When I was testing it 2 days ago, both issues were present, and now neither. Not sure what happened! Maybe we'll call it closed.
